#!/usr/bin/env ruby

require "bundler/setup"
require "quiver_toolbox"


class QuiverToolbox::CLI::Notebook
  desc "version", "Show version number"
  def version
    puts QuiverToolbox::VERSION
  end
end

QuiverToolbox::CLI::Notebook.start(ARGV)
